In [3]:
import pandas as pd
import numpy as np

In [23]:
len = 10
data_sum = np.zeros((len, len), dtype = np.int64)
data_diff = np.zeros((len, len), dtype = np.int64)
for n in range(0, len):
    for m in range (0, len):
        n2 = 2 ** (n + 1)
        m3 = 3 ** (m + 1)
        data_sum[n][m] = n2 + m3
        data_diff[n][m] = abs(n2 - m3)

result = np.append(data_sum, data_diff)     
print(data_sum)  
print(data_diff)
result = np.unique(result)
print(result)


[[    5    11    29    83   245   731  2189  6563 19685 59051]
 [    7    13    31    85   247   733  2191  6565 19687 59053]
 [   11    17    35    89   251   737  2195  6569 19691 59057]
 [   19    25    43    97   259   745  2203  6577 19699 59065]
 [   35    41    59   113   275   761  2219  6593 19715 59081]
 [   67    73    91   145   307   793  2251  6625 19747 59113]
 [  131   137   155   209   371   857  2315  6689 19811 59177]
 [  259   265   283   337   499   985  2443  6817 19939 59305]
 [  515   521   539   593   755  1241  2699  7073 20195 59561]
 [ 1027  1033  1051  1105  1267  1753  3211  7585 20707 60073]]
[[    1     7    25    79   241   727  2185  6559 19681 59047]
 [    1     5    23    77   239   725  2183  6557 19679 59045]
 [    5     1    19    73   235   721  2179  6553 19675 59041]
 [   13     7    11    65   227   713  2171  6545 19667 59033]
 [   29    23     5    49   211   697  2155  6529 19651 59017]
 [   61    55    37    17   179   665  2123  6497 1961